### ISSUE TITLE
Image in memory, points QRCODE

### ISSUE THREAD

**Issue by DiegoLimeiradaSilva** [khoren93/flutter_zxing#1]
Good afternoon, how are you? can the package take the image that was used and save it locally, or in memory so it can send it to an API? Does the location of the QRCODE points also identify?

**Comment by khoren93** [comment]
Hi @DiegoLimeiradaSilva ,
I am currently working on these features, they will be available in the next version.
Thanks.

**Comment by DiegoLimeiradaSilva** [comment]
Congratulations and thank you very much for your attention

**Comment by khoren93** [comment]
The barcode location points support finally available in 0.7.0 version )))
