### ISSUE TITLE
ReaderWidget not supported Chinese

### ISSUE THREAD

**Issue by aqiu202** [khoren93/flutter_zxing#2]
Good Morning! I have some trouble using this plugin--The ReaderWidget component does not support Chinese
![image](https://user-images.githubusercontent.com/24487480/169266746-a77f3fd5-14b3-437b-90c1-1905fcf1c0f7.png)

**Comment by khoren93** [comment]
Hi @aqiu202 

The Chinese support fixed in 0.3.1 version, please check out.

Thanks.

**Comment by aqiu202** [comment]
![image](https://user-images.githubusercontent.com/24487480/177479104-ec9f3e35-dd3c-4bb3-a047-4b4fd6e7f316.png)
try this?

**Comment by khoren93** [comment]
Thanks a lot, it worked=))
