### ISSUE TITLE
updating with recent zxing cpp 

### ISSUE THREAD

**Issue by yp25** [khoren93/flutter_zxing#22]
hi @khoren93 thank you for your contribution for making flutter project with zxing cpp.
are you planning to update your recent source code with recent zxing cpp ? I try to copy the new source code from zxing-cpp\core to flutter_zxing\ios\Classes\src\zxing\src (and CMakeLists.txt and zxing.cmake) but got many error. For example like this :
`C:/Users/home/AppData/Local/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1\locale:3689:17: note: candidate function not viable: requires 2 arguments, but 1 was provided
      byte_string to_bytes(const _Elem* __first, const _Elem* __last);
                  ^
  1 warning and 1 error generated.`

I'm still learning how to use cmake, and still trying to fix it. 
Maybe if you have a time please help to write step by step about how to updating the source code from zxing-cpp to your flutter_zxing project. Thank you

**Comment by khoren93** [comment]
Hi @yp25 ,
Thanks for your response,

I have created a new branch [dev](https://github.com/khoren93/flutter_zxing/tree/dev), updated the zxing-cpp code to the latest version and fixed build issue. 

For quickly updating the source code from zxing-cpp to the latest, you can use [init.sh](https://github.com/khoren93/flutter_zxing/blob/dev/init.sh) script.

**Comment by khoren93** [comment]
The dev branch only works for android for now, i will try to fix for iOS later.

**Comment by yp25** [comment]
@khoren93 Thank you. 
The new code zxing-cpp can decode / read micro qr code (Android wrapper), and flutter_zxing still can't. I try to modify :
extensions.dart  --> adding Format.MicroQRCode:'MicroQRCode', 
generated_bindings.dart --> adding static const int MicroQRCode = 65536;
native_zxing.h --> adding  MicroQRCode     = (1 << 16),

but still can't decode / read micro qr code. could you help which part of your code I should modify ? Thanks

**Comment by khoren93** [comment]
@yp25 I added micro qr code support. You can view changes [here](https://github.com/khoren93/flutter_zxing/commit/74b9f1429d3e594d28d9c9ba2be78615d97272d1). Thanks.

**Comment by nicoardi08** [comment]
hi @khoren93 Thank you for dev branch. I can compile it using Windows and run it on Android,

when I try to compile using MacBook M1 to run the app on iOS, I got this error

/Users/inc/flutter_project/flutter_zxing_dev_github/flutter_zxing-dev/ios/Classes/src/zxing/src/TextEncoder.cpp:12:10: fatal error: 'zueci.h' file not found
    #include "zueci.h"
             ^~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    warning: no rule to process file '/Users/inc/flutter_project/flutter_zxing_dev_github/flutter_zxing-dev/ios/Classes/src/CMakeLists.txt' of type 'text' for architecture 'arm64' (in target 'flutter_zxing' from project 'Pods')
    warning: no rule to process file '/Users/inc/flutter_project/flutter_zxing_dev_github/flutter_zxing-dev/ios/Classes/src/zxing/CMakeLists.txt' of type 'text' for architecture 'arm64' (in target 'flutter_zxing' from project 'Pods')
    warning: no rule to process file '/Users/inc/flutter_project/flutter_zxing_dev_github/flutter_zxing-dev/ios/Classes/src/zxing.cmake' of type 'text' for architecture 'arm64' (in target 'flutter_zxing' from project 'Pods')
    warning: no rule to process file '/Users/inc/flutter_project/flutter_zxing_dev_github/flutter_zxing-dev/ios/Classes/src/zxing/ZXingConfig.cmake.in' of type 'text' for architecture 'arm64' (in target 'flutter_zxing' from project 'Pods')
    warning: no rule to process file '/Users/inc/flutter_project/flutter_zxing_dev_github/flutter_zxing-dev/ios/Classes/src/zxing/ZXVersion.h.in' of type 'text' for architecture 'arm64' (in target 'flutter_zxing' from project 'Pods')

    Result bundle written to path:
    	/var/folders/sr/07n0x_rd2733jfdfldhl5g5w0000gn/T/flutter_tools.CGhB7a/flutter_ios_build_temp_dirlbSrpl/temporary_xcresult_bundle


Could not build the precompiled application for the device.
Lexical or Preprocessor Issue (Xcode): 'zueci.h' file not found
/Users/inc/flutter_project/flutter_zxing_dev_github/flutter_zxing-dev/ios/Classes/src/zxing/src/TextEncoder.cpp:11:9

any idea how to solve this ? Thanks

**Comment by khoren93** [comment]
Hi @nicoardi08 

Unfortunately at the moment I have no idea how to fix this problem for iOS. 
On the Android [CMake command](https://github.com/khoren93/flutter_zxing/blob/d15f9194b7a1b1b2b9d903a486539ae98d1c52eb/ios/Classes/src/zxing/CMakeLists.txt#L8) downloads this third part library, but iOS don't.
I will be very grateful for any help.

Thanks.

**Comment by axxel** [comment]
I noticed that you recently upgraded to zxing-cpp 2.0. There the external dependency on the zueci project has been removed and the relevant code parts have been included in zxing-cpp directly (partly to prevent issues that people are having with the sourceforge git repo).

**Comment by khoren93** [comment]
Dear @axxel 

Thank you for your work on upgrading to zxing-cpp 2.0 and for including the relevant code parts directly. This change has made a big difference and the project is now working correctly. Thank you for your help!

**Comment by yp25** [comment]
Thank you @axxel and @khoren93
