### ISSUE TITLE
Mistakes in README.md

### ISSUE THREAD

**Issue by kaboc** [khoren93/flutter_zxing#25]
```dart
import 'package:flutter_zxing/flutter_zxing.dart';

...

CodeResult? resultFromXFile = await FlutterZxing.readImagePath(xFile);
```

`FlutterZxing` looks like a class name, but it does not exist. If you mean a prefix for the library, the `as` keyword should be used.

But `as FlutterZxing` violates the [library_prefixes](https://dart-lang.github.io/linter/lints/library_prefixes.html) rule:

> DO use lowercase_with_underscores when specifying a library prefix".

Just `zxing` might be better.

```dart
import 'package:flutter_zxing/flutter_zxing.dart' as zxing;
```

Method names are also wrong. `readImagePath`, `readImagePathString` and `readImageUrl` are actually `readBarcodeImagePath`, `readBarcodeImagePathString` and `readBarcodeImageUrl`. There may be more mistakes.

**Comment by khoren93** [comment]
@kaboc I have updated the readme to the latest version of the plugin. Thanks))
