### ISSUE TITLE
Issue with Android 13 (SDK 33)

### ISSUE THREAD

**Issue by Abhinav-Satija** [khoren93/flutter_zxing#31]
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.EncoderProfiles$VideoProfile.getWidth()' on a null object reference
E/AndroidRuntime(26879): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5347)
E/AndroidRuntime(26879): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5386)
E/AndroidRuntime(26879): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
E/AndroidRuntime(26879): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime(26879): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(26879): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(26879): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
E/AndroidRuntime(26879): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(26879): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(26879): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(26879): 	at android.app.ActivityThread.main(ActivityThread.java:7898)
E/AndroidRuntime(26879): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26879): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(26879): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/AndroidRuntime(26879): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.EncoderProfiles$VideoProfile.getWidth()' on a null object reference

**Comment by lucasnsa** [comment]
Hey @Abhinav-Satija, how are you?

Possibly this bug is related to another package. See  https://github.com/flutter/flutter/issues/109769

_Try a compileSdkVersion version less than 33_

**Comment by vinhbui1** [comment]
why it still open ? Flutter team fix it official  ?

**Comment by khoren93** [comment]
Closing for now as this is already fixed.
