### ISSUE TITLE
Feature request: Desktop support

### ISSUE THREAD

**Issue by dainnilsson** [khoren93/flutter_zxing#36]
Hello! Thanks for the work on this project!

I'd like to request desktop support (windows, MacOS and Linux) in this project. I'm not sure if it's in the scope of this project to capture from video streams or not on these platforms, but I think just being able to provide an image buffer and scan it for a QR code would be very useful. I can't help with development, but I can help with testing if needed!

**Comment by khoren93** [comment]
Hi @dainnilsson 

This project uses the official [camera  plugin](https://pub.dev/packages/camera), which does not support desktop platforms at the moment. 
But in the future, when possible, I plan to add support for desktop platforms.

[Track Linux status](https://github.com/flutter/flutter/issues/41710)
[Track MacOS status](https://github.com/flutter/flutter/issues/41708)
[Track image stream support on Windows](https://github.com/flutter/flutter/issues/97542)

Thanks!

**Comment by dainnilsson** [comment]
Got it, thanks! Would it be possible to just provide an API for detecting and decoding a QR code from an image on desktop? That would be sufficient for my use case at least, and would probably be required anyway once the camera plugin supports desktop.

**Comment by khoren93** [comment]
I think it will be possible, I will work on it.

**Comment by khoren93** [comment]
Hi @dainnilsson 

Desktop platforms are now supported in the v1.0.0 beta version.
You can use this version to detect and decode QR codes from images on desktop platforms.
