### ISSUE TITLE
Barcode scan with black background issue

### ISSUE THREAD

**Issue by HoVvo** [khoren93/flutter_zxing#57]
**I have an issue scanning barcode which has a black background.**
 
The scanner don’t scan the barcode only works if background is white.

Example of  black background barcode which not able to scan.
![barcode_example](https://user-images.githubusercontent.com/17927422/207704948-7d1b1063-d9dc-40b4-aba9-9df46e393823.jpg)

**Comment by khoren93** [comment]
Hi there,

Thank you for your question and for bringing this issue to my attention.

I have released a new version v0.8.5 and would like to ask if you could please check if the issue still persists in the new version. 
You can use `ReaderWidget` with 'tryInverted: true' parameter to scan inverted codes with black background.

Thank you again for your support.
Best regards,
Khoren

**Comment by khoren93** [comment]
I am closing this issue because it has been fixed in the latest version.
Thanks for reporting the issue.
