### ISSUE TITLE
Gives Out Of Memory Exception on Android devices when left on scanning screen for long time

### ISSUE THREAD

**Issue by Ashutosh-Spark** [khoren93/flutter_zxing#60]
The SDK is giving Out of memory exception when left on the scanning screen for long time

**Comment by lucasnsa** [comment]
@Ashutosh-Spark Hi!
Please can you provide us with more information? For example android version and flutter version, how long scanning, etc?

Thanks

**Comment by Ashutosh-Spark** [comment]
Hello @lucasnsa  We are trying this on Android 10 i.e API level 29
And are using below  versions 
Flutter 3.0.5
Dart 2.17.6 
Dev tools 2.12.2

If we leave the device for more than 2 minutes it crashes and gives OOM

**Comment by lucasnsa** [comment]
I successfully simulated only using scanDelay with zero duration but I can't debug with my current environment. The problem happens after many minutes.

@khoren93 can you help us?

**Comment by khoren93** [comment]
Hi everyone,

I just released a new version of the project v0.9.1.
This new version includes the fix for a memory leak.

Please also feel free to suggest any new features or improvements that you would like to see in future releases.

Thank you for your help and for your continued support!
