### ISSUE TITLE
Camera preview is distorted on older Android devices

### ISSUE THREAD

**Issue by kaboc** [khoren93/flutter_zxing#68]
The red box in the screenshot below is a square, but it is shown as a rectangular on Android 5.1. It does not happen on my another phone with Android 10. I'm not really sure if it is related to Android versions though, because I have only those two real devices.

It didn't happen on the same device when I was using another QR scanner plugin.

**Environment:**

- Android 5.1
- flutter_zxing 0.9.1

**Reproducible code:**

```dart
import 'package:flutter/material.dart';
import 'package:flutter_zxing/flutter_zxing.dart';

void main() {
  runApp(const App());
}

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: ReaderWidget(
          onScan: (_) {},
        ),
      ),
    );
  }
}
```

**Screenshot:**

<img src="https://user-images.githubusercontent.com/20254485/210806233-00ae22f3-a6fa-4637-9f03-012de1c45c8e.jpg" height="300">

**Comment by kaboc** [comment]
I suspected that it might be because of the aspect ratio on a wider screen, but it does not seem to be the direct cause. I don't see the issue on Android 10 even if I change the aspect ratio to be wider.

<img src="https://user-images.githubusercontent.com/20254485/210809247-aec537dc-9be1-4451-b7d0-51632b8bc496.png" height="300">

```dart
@override
Widget build(BuildContext context) {
  return MaterialApp(
    home: Scaffold(
      body: AspectRatio(
        aspectRatio: 3 / 4,
        child: ReaderWidget(
          onScan: (_) {},
        ),
      ),
    ),
  );
}
```

**Comment by kaboc** [comment]
I noticed this issue was due to a bug of package:camera. The aspect ratio changes when `startImageStream()` is called. So I searched related for bug reports in the Flutter repo on GitHub and found [this](https://github.com/flutter/flutter/issues/15953).

None of the workarounds written in the page worked for me. There may be no choice but to wait for the bug to be fixed. It looks like the issue has been around for almost five years...

**Comment by khoren93** [comment]
I appreciate your thorough investigation into this issue. It's frustrating to see that the problem has persisted for so long. I'll take note of this and will proceed to close the issue. If there are any updates or changes in the future, we can reopen it. Thank you for your patience!
