### ISSUE TITLE
CMake error when adding dependency to desktop

### ISSUE THREAD

**Issue by dainnilsson** [khoren93/flutter_zxing#80]
I wanted to test out the new desktop support (#36), but as soon as I added the dependency I ran into build errors on both Windows and Linux (I haven't tested on MacOS yet). All I did was add `flutter_zxing: ^1.0.0` to pubspec.yaml, ran `flutter pub get` and then tried to build with `flutter build linux` (or windows). The error I'm getting is:

```
$ flutter build linux
💪 Building with sound null safety 💪

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
log-lib
    linked by target "flutter_zxing" in directory my-project/linux/flutter/ephemeral/.plugin_symlinks/flutter_zxing/src                                                             

CMake Generate step failed.  Build files cannot be regenerated correctly.
Building Linux application...
Unable to generate build files
```

The error on Windows is pretty much identical. Am I missing something obvious here?

**Comment by mogbebs** [comment]
hello has there been a reply to this error message. I am experiencing the same issue. Any help would be greatly appreciated
