### ISSUE TITLE
Front camera

### ISSUE THREAD

**Issue by DevTuliPark** [khoren93/flutter_zxing#81]
Hi, 
How do I activate the front camera to read the qrcode?

**Comment by khoren93** [comment]
This feature will be available in the next version. Thank you for your interest.

**Comment by khoren93** [comment]
Available in v1.0.1

**Comment by DevTuliPark** [comment]
Hi, 
would it be possible to switch the camera from code? 
If yes, could you show me an example? 
Thank you.
