### ISSUE TITLE
Error while building example 

### ISSUE THREAD

**Issue by atulraj85** [khoren93/flutter_zxing#85]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_zxing:buildCMakeDebug[arm64-v8a]'.
> Build command failed.
  Error while executing process /home/user/Android/Sdk/cmake/3.18.1/bin/ninja with arguments {-C /home/user/Desktop/My World/XMPP gsoc/flutter_zxing/android/.cxx/Debug/6m632u53/arm64-v8a flutter_zxing}
  ninja: Entering directory `/home/user/Desktop/My World/XMPP gsoc/flutter_zxing/android/.cxx/Debug/6m632u53/arm64-v8a'
  [1/83] Building CXX object zxing/core/CMakeFiles/ZXing.dir/src/TextEncoder.cpp.o
  [2/83] Building CXX object zxing/core/CMakeFiles/ZXing.dir/src/aztec/AZToken.cpp.o
  [3/83] Building CXX object zxing/core/CMakeFiles/ZXing.dir/src/aztec/AZReader.cpp.o
  FAILED: zxing/core/CMakeFiles/ZXing.dir/src/aztec/AZReader.cpp.o 
  /home/user/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --gcc-toolchain=/home/user/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/user/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/sysroot  -I"/home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src" -Izxing/core -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -O0 -fno-limit-debug-info  -fPIC -DZXING_BUILD_READERS -DZXING_BUILD_WRITERS -Wall -Wextra -Wno-missing-braces -Werror=undef -Werror=return-type -pthread -std=gnu++17 -MD -MT zxing/core/CMakeFiles/ZXing.dir/src/aztec/AZReader.cpp.o -MF zxing/core/CMakeFiles/ZXing.dir/src/aztec/AZReader.cpp.o.d -o zxing/core/CMakeFiles/ZXing.dir/src/aztec/AZReader.cpp.o -c '/home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src/aztec/AZReader.cpp'
  In file included from /home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src/aztec/AZReader.cpp:13:
  In file included from /home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src/BinaryBitmap.h:13:
  /snap/flutter/current/usr/include/c++/9/memory:121:25: error: cast from pointer to smaller type 'uintptr_t' (aka 'unsigned int') loses information
    const auto __intptr = reinterpret_cast<uintptr_t>(__ptr);
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
  [4/83] Building CXX object zxing/core/CMakeFiles/ZXing.dir/src/MultiFormatReader.cpp.o
  FAILED: zxing/core/CMakeFiles/ZXing.dir/src/MultiFormatReader.cpp.o 
  /home/user/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --gcc-toolchain=/home/user/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/user/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/sysroot  -I"/home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src" -Izxing/core -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -O0 -fno-limit-debug-info  -fPIC -DZXING_BUILD_READERS -DZXING_BUILD_WRITERS -Wall -Wextra -Wno-missing-braces -Werror=undef -Werror=return-type -pthread -std=gnu++17 -MD -MT zxing/core/CMakeFiles/ZXing.dir/src/MultiFormatReader.cpp.o -MF zxing/core/CMakeFiles/ZXing.dir/src/MultiFormatReader.cpp.o.d -o zxing/core/CMakeFiles/ZXing.dir/src/MultiFormatReader.cpp.o -c '/home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src/MultiFormatReader.cpp'
  In file included from /home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src/MultiFormatReader.cpp:7:
  In file included from /home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src/MultiFormatReader.h:12:
  /snap/flutter/current/usr/include/c++/9/memory:121:25: error: cast from pointer to smaller type 'uintptr_t' (aka 'unsigned int') loses information
    const auto __intptr = reinterpret_cast<uintptr_t>(__ptr);
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
  [5/83] Building CXX object zxing/core/CMakeFiles/ZXing.dir/src/GlobalHistogramBinarizer.cpp.o
  FAILED: zxing/core/CMakeFiles/ZXing.dir/src/GlobalHistogramBinarizer.cpp.o 
  /home/user/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --gcc-toolchain=/home/user/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/user/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/sysroot  -I"/home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src" -Izxing/core -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -O0 -fno-limit-debug-info  -fPIC -DZXING_BUILD_READERS -DZXING_BUILD_WRITERS -Wall -Wextra -Wno-missing-braces -Werror=undef -Werror=return-type -pthread -std=gnu++17 -MD -MT zxing/core/CMakeFiles/ZXing.dir/src/GlobalHistogramBinarizer.cpp.o -MF zxing/core/CMakeFiles/ZXing.dir/src/GlobalHistogramBinarizer.cpp.o.d -o zxing/core/CMakeFiles/ZXing.dir/src/GlobalHistogramBinarizer.cpp.o -c '/home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src/GlobalHistogramBinarizer.cpp'
  In file included from /home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src/GlobalHistogramBinarizer.cpp:7:
  In file included from /home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src/GlobalHistogramBinarizer.h:9:
  In file included from /home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src/BinaryBitmap.h:13:
  /snap/flutter/current/usr/include/c++/9/memory:121:25: error: cast from pointer to smaller type 'uintptr_t' (aka 'unsigned int') loses information
    const auto __intptr = reinterpret_cast<uintptr_t>(__ptr);
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
  [6/83] Building CXX object zxing/core/CMakeFiles/ZXing.dir/src/aztec/AZEncoder.cpp.o
  [7/83] Building CXX object zxing/core/CMakeFiles/ZXing.dir/src/ReedSolomonEncoder.cpp.o
  [8/83] Building CXX object zxing/core/CMakeFiles/ZXing.dir/src/MultiFormatWriter.cpp.o
  FAILED: zxing/core/CMakeFiles/ZXing.dir/src/MultiFormatWriter.cpp.o 
  /home/user/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --gcc-toolchain=/home/user/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/user/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/sysroot  -I"/home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src" -Izxing/core -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -O0 -fno-limit-debug-info  -fPIC -DZXING_BUILD_READERS -DZXING_BUILD_WRITERS -Wall -Wextra -Wno-missing-braces -Werror=undef -Werror=return-type -pthread -std=gnu++17 -MD -MT zxing/core/CMakeFiles/ZXing.dir/src/MultiFormatWriter.cpp.o -MF zxing/core/CMakeFiles/ZXing.dir/src/MultiFormatWriter.cpp.o.d -o zxing/core/CMakeFiles/ZXing.dir/src/MultiFormatWriter.cpp.o -c '/home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src/MultiFormatWriter.cpp'
  In file included from /home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src/MultiFormatWriter.cpp:20:
  In file included from /home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src/pdf417/PDFWriter.h:12:
  /snap/flutter/current/usr/include/c++/9/memory:121:25: error: cast from pointer to smaller type 'uintptr_t' (aka 'unsigned int') loses information
    const auto __intptr = reinterpret_cast<uintptr_t>(__ptr);
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
  [9/83] Building CXX object zxing/core/CMakeFiles/ZXing.dir/src/HybridBinarizer.cpp.o
  FAILED: zxing/core/CMakeFiles/ZXing.dir/src/HybridBinarizer.cpp.o 
  /home/user/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --gcc-toolchain=/home/user/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/user/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/sysroot  -I"/home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src" -Izxing/core -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -O0 -fno-limit-debug-info  -fPIC -DZXING_BUILD_READERS -DZXING_BUILD_WRITERS -Wall -Wextra -Wno-missing-braces -Werror=undef -Werror=return-type -pthread -std=gnu++17 -MD -MT zxing/core/CMakeFiles/ZXing.dir/src/HybridBinarizer.cpp.o -MF zxing/core/CMakeFiles/ZXing.dir/src/HybridBinarizer.cpp.o.d -o zxing/core/CMakeFiles/ZXing.dir/src/HybridBinarizer.cpp.o -c '/home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src/HybridBinarizer.cpp'
  In file included from /home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src/HybridBinarizer.cpp:7:
  In file included from /home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src/HybridBinarizer.h:9:
  In file included from /home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src/GlobalHistogramBinarizer.h:9:
  In file included from /home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src/BinaryBitmap.h:13:
  /snap/flutter/current/usr/include/c++/9/memory:121:25: error: cast from pointer to smaller type 'uintptr_t' (aka 'unsigned int') loses information
    const auto __intptr = reinterpret_cast<uintptr_t>(__ptr);
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
  [10/83] Building CXX object zxing/core/CMakeFiles/ZXing.dir/src/Result.cpp.o
  FAILED: zxing/core/CMakeFiles/ZXing.dir/src/Result.cpp.o 
  /home/user/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --gcc-toolchain=/home/user/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/user/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/sysroot  -I"/home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src" -Izxing/core -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -O0 -fno-limit-debug-info  -fPIC -DZXING_BUILD_READERS -DZXING_BUILD_WRITERS -Wall -Wextra -Wno-missing-braces -Werror=undef -Werror=return-type -pthread -std=gnu++17 -MD -MT zxing/core/CMakeFiles/ZXing.dir/src/Result.cpp.o -MF zxing/core/CMakeFiles/ZXing.dir/src/Result.cpp.o.d -o zxing/core/CMakeFiles/ZXing.dir/src/Result.cpp.o -c '/home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src/Result.cpp'
  In file included from /home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src/Result.cpp:9:
  In file included from /home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src/DecoderResult.h:13:
  /snap/flutter/current/usr/include/c++/9/memory:121:25: error: cast from pointer to smaller type 'uintptr_t' (aka 'unsigned int') loses information
    const auto __intptr = reinterpret_cast<uintptr_t>(__ptr);
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
  [11/83] Building CXX object zxing/core/CMakeFiles/ZXing.dir/src/ReadBarcode.cpp.o
  FAILED: zxing/core/CMakeFiles/ZXing.dir/src/ReadBarcode.cpp.o 
  /home/user/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --gcc-toolchain=/home/user/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/user/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/sysroot  -I"/home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src" -Izxing/core -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -O0 -fno-limit-debug-info  -fPIC -DZXING_BUILD_READERS -DZXING_BUILD_WRITERS -Wall -Wextra -Wno-missing-braces -Werror=undef -Werror=return-type -pthread -std=gnu++17 -MD -MT zxing/core/CMakeFiles/ZXing.dir/src/ReadBarcode.cpp.o -MF zxing/core/CMakeFiles/ZXing.dir/src/ReadBarcode.cpp.o.d -o zxing/core/CMakeFiles/ZXing.dir/src/ReadBarcode.cpp.o -c '/home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src/ReadBarcode.cpp'
  In file included from /home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src/ReadBarcode.cpp:9:
  In file included from /home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src/GlobalHistogramBinarizer.h:9:
  In file included from /home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src/BinaryBitmap.h:13:
  /snap/flutter/current/usr/include/c++/9/memory:121:25: error: cast from pointer to smaller type 'uintptr_t' (aka 'unsigned int') loses information
    const auto __intptr = reinterpret_cast<uintptr_t>(__ptr);
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
  [12/83] Building CXX object zxing/core/CMakeFiles/ZXing.dir/src/BinaryBitmap.cpp.o
  FAILED: zxing/core/CMakeFiles/ZXing.dir/src/BinaryBitmap.cpp.o 
  /home/user/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --gcc-toolchain=/home/user/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/user/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/sysroot  -I"/home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src" -Izxing/core -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -O0 -fno-limit-debug-info  -fPIC -DZXING_BUILD_READERS -DZXING_BUILD_WRITERS -Wall -Wextra -Wno-missing-braces -Werror=undef -Werror=return-type -pthread -std=gnu++17 -MD -MT zxing/core/CMakeFiles/ZXing.dir/src/BinaryBitmap.cpp.o -MF zxing/core/CMakeFiles/ZXing.dir/src/BinaryBitmap.cpp.o.d -o zxing/core/CMakeFiles/ZXing.dir/src/BinaryBitmap.cpp.o -c '/home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src/BinaryBitmap.cpp'
  In file included from /home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src/BinaryBitmap.cpp:6:
  In file included from /home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src/BinaryBitmap.h:13:
  /snap/flutter/current/usr/include/c++/9/memory:121:25: error: cast from pointer to smaller type 'uintptr_t' (aka 'unsigned int') loses information
    const auto __intptr = reinterpret_cast<uintptr_t>(__ptr);
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
  [13/83] Building CXX object zxing/core/CMakeFiles/ZXing.dir/src/aztec/AZDecoder.cpp.o
  FAILED: zxing/core/CMakeFiles/ZXing.dir/src/aztec/AZDecoder.cpp.o 
  /home/user/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --gcc-toolchain=/home/user/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/user/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/sysroot  -I"/home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src" -Izxing/core -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -O0 -fno-limit-debug-info  -fPIC -DZXING_BUILD_READERS -DZXING_BUILD_WRITERS -Wall -Wextra -Wno-missing-braces -Werror=undef -Werror=return-type -pthread -std=gnu++17 -MD -MT zxing/core/CMakeFiles/ZXing.dir/src/aztec/AZDecoder.cpp.o -MF zxing/core/CMakeFiles/ZXing.dir/src/aztec/AZDecoder.cpp.o.d -o zxing/core/CMakeFiles/ZXing.dir/src/aztec/AZDecoder.cpp.o -c '/home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src/aztec/AZDecoder.cpp'
  In file included from /home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src/aztec/AZDecoder.cpp:14:
  In file included from /home/user/Desktop/My World/XMPP gsoc/flutter_zxing/src/zxing/core/src/DecoderResult.h:13:
  /snap/flutter/current/usr/include/c++/9/memory:121:25: error: cast from pointer to smaller type 'uintptr_t' (aka 'unsigned int') loses information
    const auto __intptr = reinterpret_cast<uintptr_t>(__ptr);
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
  [14/83] Building CXX object zxing/core/CMakeFiles/ZXing.dir/src/aztec/AZDetector.cpp.o
  [15/83] Building CXX object zxing/core/CMakeFiles/ZXing.dir/src/aztec/AZHighLevelEncoder.cpp.o
  [16/83] Building CXX object zxing/core/CMakeFiles/ZXing.dir/src/aztec/AZWriter.cpp.o
  ninja: build stopped: subcommand failed.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
Running Gradle task 'assembleDebug'...                              9.5s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by leccyril** [comment]
what was the issue ? i have the same

**Comment by atulraj85** [comment]
I had this isssue quite a long ago. It was due to the way I installed Flutter. I installed it manually then it worked.
