### ISSUE TITLE
Switch Camera

### ISSUE THREAD

**Issue by DevTuliPark** [khoren93/flutter_zxing#86]
Hi,
would it be possible to switch the camera from code?
If yes, could you show me an example?
Thank you.

**Comment by khoren93** [comment]
Dear @DevTuliPark,

I just wanted to inform you that I have incorporated a new feature in version v1.1.1. You can now easily set lensDirection in ReaderWidget.

Thank you for your attention.

**Comment by DevTuliPark** [comment]
Thank you for the work.
