### ISSUE TITLE
ReaderWidget onScan never called on iOS 

### ISSUE THREAD

**Issue by dhiyaulhaqZA** [khoren93/flutter_zxing#90]
Hi, I can't scan QRCode on iOS. ReaderWidget onScan is never called, it is always scanning.

flutter_zxing: ^1.1.2

Tested on iPhone XR (iOS 16.1.2)

Works fine on my Android phone.

**Comment by iulianxpopa** [comment]
Same here! (tested only on iOS for now)

**Comment by softkot** [comment]
Upgrading from 1.0.0 to 1.1.1 broke ios code recognition, meanwile android works fine.

**Comment by khoren93** [comment]
Hello,

I'm pleased to announce that version 1.2.0 is now available. This latest version has been released to address the iOS detection issue that some users have been experiencing.

To temporarily resolve the issue, I've downgraded the image version from v4.0 to v3.0. Please note that this is a temporary fix and a more permanent solution will be provided in the next releases.

If you encounter any issues or have any feedback about the new version, please let me know.

Thank you for your support!

Best regards,
Khoren

**Comment by dhiyaulhaqZA** [comment]
Fixed on v1.2.0

Tested on iPhone XR (iOS 16.1.2). Thanks
