### ISSUE TITLE
Image v4

### ISSUE THREAD

**Issue by provokateurin** [khoren93/flutter_zxing#94]
In https://github.com/khoren93/flutter_zxing/commit/949dc88407754f4709deee823d35639cdbbfe36b the image dependency was downgraded to v3 again. Can we get v4 again? I'm trying to use this libary together with other libraries that depend on image v4.

**Comment by JustMyLive** [comment]
I want that too....

**Comment by provokateurin** [comment]
@khoren93 I guess this can be closed with https://github.com/khoren93/flutter_zxing/commit/b1c4db8dc8824b16bff01f68864c515dbd785e3b?

**Comment by khoren93** [comment]
Certainly! With v1.4.0, this issue has been resolved. Thanks!
